# Generated by Django 5.1.3 on 2025-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariomodel',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='key_expressions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='scoring',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='student_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='vocabulary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
