# Generated by Django 5.1.3 on 2024-12-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classcontentmodel',
            old_name='class_model',
            new_name='class_id',
        ),
        migrations.AddField(
            model_name='classcontentmodel',
            name='stats',
            field=models.BooleanField(default=False),
        ),
    ]
