# Generated by Django 5.1.3 on 2024-11-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_img_cover_classmodel_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classmodel',
            old_name='lesson_name',
            new_name='class_name',
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='dashboard.coursemodel'),
        ),
        migrations.AlterField(
            model_name='layoutmodel',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='class_audio/'),
        ),
    ]
