# Generated by Django 5.1.3 on 2025-01-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_scenariomodel_additional_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenariomodel',
            old_name='class_model',
            new_name='class_id',
        ),
    ]
