# Generated by Django 5.1.3 on 2024-12-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_classcontentmodel_audio_classcontentmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcontentmodel',
            name='audio_transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classcontentmodel',
            name='video_transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
