# Generated by Django 5.1.3 on 2024-11-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_lesson_name_classmodel_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriestaskmodel',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='bullet_points',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='bullet_points',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fillinthegapstaskmodel',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layoutmodel',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicemodel',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderingtaskmodel',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textblockmodel',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trueorfalsemodel',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
