# Generated by Django 5.1.3 on 2024-11-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_categoriestaskmodel_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='bullet_points',
            field=models.JSONField(blank=True, help_text="Formato: ['punto 1', 'punto 2', ...]", null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='bullet_points',
            field=models.JSONField(help_text="Formato: ['punto 1', 'punto 2', ...]"),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='layoutmodel',
            name='audio_script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layoutmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='textblockmodel',
            name='title',
            field=models.CharField(blank=True, help_text='Título del bloque de texto', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='script',
            field=models.TextField(blank=True, help_text='Transcripción de lo que se dice en el video', null=True),
        ),
    ]
