# Generated by Django 5.1.3 on 2024-12-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_classcontentmodel_audio_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcontentmodel',
            name='embed_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
