# Generated by Django 5.1.3 on 2024-11-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_classmodel_bullet_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='bullet_points',
            field=models.JSONField(blank=True, help_text="Formato: ['punto 1', 'punto 2', ...]", null=True),
        ),
    ]
