# Generated by Django 5.1.3 on 2024-12-31 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_classcontentmodel_content_type_scenariomodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormattedTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(help_text='Contenido con formato HTML/TipTap')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatted_texts', to='dashboard.classmodel')),
            ],
            options={
                'verbose_name': 'Texto Formateado',
                'verbose_name_plural': 'Textos Formateados',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ConversationHistory',
        ),
    ]
