# Generated by Django 5.1.3 on 2025-01-19 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_studentmodel_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to='dashboard.studentmodel')),
            ],
        ),
    ]
