# Generated by Django 5.1.3 on 2024-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_coursemodel_bullet_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='task_media/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='categoriestaskmodel',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='categories_tasks', to='dashboard.mediamodel'),
        ),
        migrations.AddField(
            model_name='fillinthegapstaskmodel',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='fill_in_the_gaps_tasks', to='dashboard.mediamodel'),
        ),
        migrations.AddField(
            model_name='multiplechoicemodel',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='multiple_choice_tasks', to='dashboard.mediamodel'),
        ),
        migrations.AddField(
            model_name='orderingtaskmodel',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='ordering_tasks', to='dashboard.mediamodel'),
        ),
        migrations.AddField(
            model_name='trueorfalsemodel',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='true_or_false_tasks', to='dashboard.mediamodel'),
        ),
    ]
