# Generated by Django 5.1.3 on 2024-12-01 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_mediamodel_categoriestaskmodel_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLayoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del video', max_length=200)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, help_text='Archivo de video', null=True, upload_to='videos/')),
                ('script', models.TextField(blank=True, help_text='Transcripción de lo que se dice en el video', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.classmodel')),
            ],
        ),
        migrations.RenameModel(
            old_name='TextBlockModel',
            new_name='TextBlockLayoutModel',
        ),
        migrations.DeleteModel(
            name='VideoModel',
        ),
    ]
