# Generated by Django 5.1.3 on 2024-12-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_videolayoutmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoicemodel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='multiplechoicemodel',
            unique_together={('layout',)},
        ),
        migrations.RemoveField(
            model_name='multiplechoicemodel',
            name='order',
        ),
    ]
