# Generated by Django 5.1.3 on 2024-12-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_multiplechoicemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaBlockVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, help_text='Archivo de video', null=True, upload_to='videos/')),
                ('script', models.TextField(blank=True, help_text='Transcripción de lo que se dice en el video', null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='multimedia_block_videos/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='multiplechoicemodel',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='multiplechoicemodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='multiplechoicemodel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='multiplechoicemodel',
            unique_together={('layout', 'order')},
        ),
    ]
