# Generated by Django 5.1.3 on 2024-12-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_multimediablockvideomodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoicemodel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='multiplechoicemodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='multiplechoicemodel',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_multiple_choice_tasks/'),
        ),
        migrations.AddField(
            model_name='multiplechoicemodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover_multiple_choice_tasks/'),
        ),
        migrations.AddField(
            model_name='multiplechoicemodel',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicemodel',
            name='stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplechoicemodel',
            name='tittle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicemodel',
            name='question',
            field=models.JSONField(),
        ),
        migrations.RemoveField(
            model_name='multiplechoicemodel',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='multiplechoicemodel',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='multiplechoicemodel',
            name='media',
        ),
        migrations.RemoveField(
            model_name='multiplechoicemodel',
            name='order',
        ),
    ]
